# Variablen und Eingaben

In [1]:
3 + 4

7

In [3]:
import tensorflow as tf

In [2]:
2 * 2

4

In [3]:
11.4 - 7.9

3.5

In [4]:
888/271

3.2767527675276753

In [5]:
print("Ich lerne Python!")

Ich lerne Python!


In [6]:
print("Pi ist definiert als 3,14159...")

Pi ist definiert als 3,14159...


In [7]:
x = 5
x + 15 - 3

17

In [8]:
y = 7.2
z = x + y

print(z)

12.2


In [9]:
# Das ist ein Kommentar
# Er wird nicht mit ausgeführt

"""
Das
hier
auch
"""

y = 7.2
z = x + y

print(z)

12.2


In [10]:
name = input("Wie heißt du? ")

print(name)

Wie heißt du? Tim
Tim


In [1]:
name = input("Wie heißt du? ")
age = input("Wie alt bist du? ")

print("Du heißt", name, "und bist", age, "Jahre alt")

Wie heißt du? Tim
Wie alt bist du? 25
Du heißt Tim und bist 25 Jahre alt


In [12]:
name = input("Wie heißt du? ")

len(name)

Wie heißt du? Tim


3

In [2]:
age = input("Wie alt bist du? ")
age = age + 1

print ("Nächsten Geburtstag wirst du", age)

Wie alt bist du? 25


TypeError: can only concatenate str (not "int") to str

In [3]:
age = int(input("Wie alt bist du? "))
age = age + 1

print ("Nächsten Geburtstag wirst du", age)

Wie alt bist du? 26
Nächsten Geburtstag wirst du 27


In [15]:
centigrate = float(input("Nenne eine Temperatur in Grad Celsius "))
kelvin = centigrate - 273.15

print (centigrate, "Grad Celsius entspricht", kelvin, "Kelvin")

Nenne eine Temperatur in Grad Celsius 23.4
23.4 Grad Celsius entspricht -249.74999999999997 Kelvin


# Mathematik

In [16]:
a = 10**2
b = 7**3
c = 10**-4

print(a, b, c)

100 343 0.0001


In [17]:
100**0.5

10.0

In [18]:
import math

math.sqrt(100)

10.0

In [19]:
print("Pi:", math.pi)

print("e:", math.e)

Pi: 3.141592653589793
e: 2.718281828459045


In [20]:
print(round(math.pi, 2))

print(round(math.e, 5))

print(round(12.345, 0))

3.14
2.71828
12.0


In [21]:
num1 = int(input("Nenne eine erste Zahl: "))
num2 = int(input("Nenne eine zweite Zahl: "))

result = num1//num2
remainder = num1%num2

print(num1, "geteilt durch", num2, "ist", result, "Rest", remainder)

Nenne eine erste Zahl: 17
Nenne eine zweite Zahl: 4
17 geteilt durch 4 ist 4 Rest 1


# If-Anweisungen

In [22]:
x = 5

if x < 0:
    print (x, "ist eine negative Zahl")
elif x == 0:
    print (x, "ist 0")
else:
    print (x, "ist eine positive Zahl")

5 ist eine positive Zahl


In [23]:
name1 = input("Wie heißt du? ")

length = len(name1)

if length < 5:
    print (name1, "ist ein eher kurzer Name")
else:
    print (name1, "ist ein eher langer Name")
    
name2 = input("Wie heißt du? ")

length = len(name2)

if length < 5:
    print (name2, "ist ein eher kurzer Name")
else:
    print (name2, "ist ein eher langer Name")

Wie heißt du? Tim
Tim ist ein eher kurzer Name
Wie heißt du? Laura
Laura ist ein eher langer Name


In [24]:
subject = input("Was ist deine präferierte medizinische Fachrichtung? ")

if subject == "Innere Medizin" or subject == "innere Medizin" or subject == "Innere":
    print ("Ich mag auch innere Medizin!")
else:
    print (subject, "ist nicht so meins - ich präferiere innere Medizin")

Was ist deine präferierte medizinische Fachrichtung? Neurologie
Neurologie ist nicht so meins - ich präferiere innere Medizin


# For-Schleifen

In [25]:
for i in range (1,5):
    print(i)

1
2
3
4


In [26]:
for i in range (1,10,2):
    print(i)

1
3
5
7
9


In [27]:
for i in range (0,5):
    print("Python")

Python
Python
Python
Python
Python


In [28]:
num = int(input("Nenne eine Zahl: "))

if num <=5:
    for i in range (1,num+1):
        print(i)
else:
    print("Nicht genug Platz")

Nenne eine Zahl: 4
1
2
3
4


# While-Schleifen

In [29]:
num = 0

while num <= 5:
    num = num + 1
    print(num)

1
2
3
4
5
6


In [4]:
again = "Ja"

while again == "Ja" or again == "ja":
    print("Weiter geht's!")
    again = input("Möchtest du noch einmal? ")

print("Das war's")

Weiter geht's!
Möchtest du noch einmal? Ja
Weiter geht's!
Möchtest du noch einmal? ja
Weiter geht's!
Möchtest du noch einmal? nein
Das war's


In [2]:
again = "Ja"

while True:
    if again == "Ja" or again == "ja":
        print("Weiter geht's!")
        again = input("Möchtest du noch einmal? ")
    else:
        break

print("Das war's")

Weiter geht's!
Möchtest du noch einmal? Ja
Weiter geht's!
Möchtest du noch einmal? ja
Weiter geht's!
Möchtest du noch einmal? nein
Das war's


# Tuple, Listen, Dictionaries

## Tuple

In [4]:
organ_tuple = ("Gehirn", "Lunge", "Herz", "Leber")

print(organ_tuple)

('Gehirn', 'Lunge', 'Herz', 'Leber')


In [5]:
print(organ_tuple[3])

Leber


In [6]:
len(organ_tuple)

4

## Listen

In [ ]:
organ_list = ["Gehirn", "Lunge", "Herz", "Leber"]

print(organ_list)

In [ ]:
print(organ_list[3])

In [ ]:
len(organ_list)

In [ ]:
organ_list.append("Niere")

print(organ_list)

In [ ]:
organ_list.insert(0, "Darm")

print(organ_list)

In [ ]:
del organ_list[1]

print(organ_list)

In [ ]:
organ_list.sort()

print(organ_list)

In [ ]:
numbers = []

for i in range(3):
    num = int(input("Gib eine Zahl ein: "))
    numbers.append(num)

while True:
    again = input("Möchtest du eine weitere Zahl hinzufügen? ")
    if again == "Ja" or again == "ja":
        num = int(input("Gib eine weitere Zahl ein: "))
        numbers.append(num)
    else:
        break
    
numbers.sort()

print(numbers)

In [ ]:
two_dim_list = [[1, 2, 3], 
                [4, 5, 6]]

print(two_dim_list)

In [ ]:
three_dim_list = [[[1, 2, 3], 
                   [4, 5, 6]], 
             
                  [[7, 8, 9], 
                   [10, 11, 12]]]

print(three_dim_list)

## Dictionaries

In [ ]:
organ_dictionary = {1: "Gehirn", 2: "Lunge", 6: "Herz", 4: "Leber"}

print(organ_dictionary)

In [ ]:
print(organ_dictionary[6])

In [ ]:
len(organ_dictionary)

In [ ]:
organ_dictionary[3] = "Milz"

print(organ_dictionary)

In [ ]:
organ_dictionary[2] = "Magen"

print(organ_dictionary)

In [ ]:
sorted_dictionary = dict(sorted(organ_dictionary.items()))

print(sorted_dictionary)

In [ ]:
two_dim_dict = {1: {"A": 1, "B": 2, "C": 3}, 
                2: {"A": 4, "B": 5, "C": 6}}

print(two_dim_dict)

In [ ]:
three_dim_dict = {1: {1: {"A": 1, "B": 2, "C": 3}, 
                      2: {"A": 4, "B": 5, "C": 6}}, 
                  
                  2: {3: {"A": 1, "B": 2, "C": 3}, 
                      4: {"A": 4, "B": 5, "C": 6}}}

print(three_dim_dict)

# Arrays

In [ ]:
import numpy as np

In [ ]:
one_dim_array = np.array([1, 2, 3])

print(one_dim_array)

print("Dimension:", one_dim_array.ndim)

print("Shape:", one_dim_array.shape)

In [ ]:
two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8 , 9]])

print(two_dim_array)

print("Dimension:", two_dim_array.ndim)

print("Shape:", two_dim_array.shape)

In [ ]:
three_dim_array = np.array([[[1, 2, 3],
                            [4, 5, 6],
                            [7, 8 , 9]], 
                          
                           [[1, 2, 3],
                            [4, 5, 6],
                            [7, 8 , 9]]])

print(three_dim_array)

print("Dimension:", three_dim_array.ndim)

print("Shape:", three_dim_array.shape)

In [ ]:
two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6]])

print("Shape:", two_dim_array.shape)

print("Zweite Spalte:", two_dim_array[:, 1])

In [ ]:
two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8 , 9]])

print(two_dim_array * 2)
print()
print(two_dim_array + 5)

# Lösungen zu den Aufgaben

In [8]:
# Aufgabe 1

name = input("Vorname: ")
surname = input("Nachname: ")

print("Hallo,", name, surname)

Vorname: Laura
Nachname: Velezmoro
Hallo, Laura Velezmoro


In [9]:
# Aufgabe 2

bill = float(input("Wie viel Euro hat das Abendessen gekostet? "))
guests = int(input("Wie viele haben zu Abend gegessen? "))

priceperperson = bill/guests

print ("Jede Person muss", priceperperson, "Euro zahlen")

Wie viel Euro hat das Abendessen gekostet? 35.30
Wie viele haben zu Abend gegessen? 2
Jede Person muss 17.65 Euro zahlen


In [11]:
# Aufgabe 3

x = int(input("Nenne einen x-Wert:"))
y = 3 * (x**2) + 3

print("y =", y)

Nenne einen x-Wert:5
y = 78


In [13]:
# Aufgabe 4

import math

radius = int(input("Definiere einen Radius: "))
height = int(input("Definiere eine Höhe: "))

zylinder = (math.pi * (radius**2)) * height

print(int(zylinder))

Definiere einen Radius: 2
Definiere eine Höhe: 4
50


In [15]:
# Aufgabe 5

number = int(input("Bitte nenne eine Zahl zwischen 5 und 10: "))

if number <= 5:
    print("Zu klein")
elif number >= 10:
    print("Zu groß")
else: 
    print("Vielen Dank")

Bitte nenne eine Zahl zwischen 5 und 10: 11
Zu groß


In [16]:
# Aufgabe 6

age = int(input("Wie alt bist du? "))

if age < 16:
    print("Du darfst keinen Alkohol trinken")
elif age >= 16 and age < 18:
    print("Du darfst Bier und Wein trinken")
else:
    print("Du darfst Bier, Wein und Schnaps trinken - Prost!")

Wie alt bist du? 24
Du darfst Bier, Wein und Schnaps trinken - Prost!


In [17]:
# Aufgabe 7

name = input("Wie heißt du: ")

num = int(input("Nenne eine Zahl: "))

for i in range (1, num+1):
    print(name)

Wie heißt du: Tim
Nenne eine Zahl: 3
Tim
Tim
Tim


In [2]:
# Aufgabe 8

num = int(input("Wie viele Patient*innen sollen operiert werden? "))

if num <= 10:
    for i in range (1,num+1):
        name = input("Wie lautet der nächste Name? ")
        print(name, "wurde zum OP-Plan hinzugefügt")
        print()
else:
    print("Zu viele Patient*innen")

Wie viele Patient*innen sollen operiert werden? 4
Wie lautet der nächste Name? Frau Fischer
Frau Fischer wurde zum OP-Plan hinzugefügt

Wie lautet der nächste Name? Herr Meier
Herr Meier wurde zum OP-Plan hinzugefügt

Wie lautet der nächste Name? Frau Yilmaz
Frau Yilmaz wurde zum OP-Plan hinzugefügt

Wie lautet der nächste Name? Herr Li
Herr Li wurde zum OP-Plan hinzugefügt



In [21]:
# Aufgabe 9

num = int(input("Nenne eine Zahl: "))

again = "Ja"

while again == "Ja" or again == "ja":
    num2 = int(input("Nenne eine weitere Zahl: "))
    num = num + num2
    again = input("Möchtest du eine Zahl hinzuaddieren? ")

print("Die Summe beträgt", num)

Nenne eine Zahl: 5
Nenne eine weitere Zahl: 3
Möchtest du eine Zahl hinzuaddieren? ja
Nenne eine weitere Zahl: 2
Möchtest du eine Zahl hinzuaddieren? nein
Die Summe beträgt 10


In [23]:
# Aufgabe 10

medical_field = ["Radiologie", "Kardiologie", "Dermatologie"]

new = input("Nenne eine medizinische Fachrichtung: ")

if new not in medical_field:
    medical_field.append(new)

print(medical_field)

Nenne eine medizinische Fachrichtung: Radiologie
['Radiologie', 'Kardiologie', 'Dermatologie']


In [24]:
# Aufgabe 11

OP_Plan = []

for i in range(3):
    name = input("Gib einen Namen ein: ")
    OP_Plan.append(name)

while True:
    again = input("Möchtest du einen weiteren Namen hinzufügen? ")
    if again == "Ja" or again == "ja":
        name = input("Gib eine weiteren Namen ein: ")
        OP_Plan.append(name)
    else:
        break
    
OP_Plan.sort()

print(OP_Plan)

Gib einen Namen ein: Meier
Gib einen Namen ein: Fischer
Gib einen Namen ein: Müller
Möchtest du einen weiteren Namen hinzufügen? ja
Gib eine weiteren Namen ein: Weber
Möchtest du einen weiteren Namen hinzufügen? nein
['Fischer', 'Meier', 'Müller', 'Weber']


In [25]:
# Aufgabe 12

medical_field = {1: "Radiologie", 2: "Kardiologie", 3: "Dermatologie"}

new = input("Nenne eine medizinische Fachrichtung: ")

if new not in medical_field.values():
    medical_field[4] = new

print(medical_field)

Nenne eine medizinische Fachrichtung: Onkologie
{1: 'Radiologie', 2: 'Kardiologie', 3: 'Dermatologie', 4: 'Onkologie'}


In [26]:
# Aufgabe 13

import numpy as np

two_dim_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9],
                          [10, 11, 12]])

print(two_dim_array)

print("Shape:", two_dim_array.shape)

print("Erste zwei Zeilen", two_dim_array[0:2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Erste zwei Zeilen [[1 2 3]
 [4 5 6]]


In [27]:
# Aufgabe 14

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

y = 2 * A - 4

print(y)

[[-2  0  2]
 [ 4  6  8]]


In [28]:
# Aufgabe 15

import math

A = np.array([[1, 2, 3],
              [4, 5, 6]])

y = 1/(1 + (math.e**(-A)))

print(y)

[[0.73105858 0.88079708 0.95257413]
 [0.98201379 0.99330715 0.99752738]]
